apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ncgroupsync
  annotations:
    github.com/project-slug: hghtwr/ncgroupsync
spec:
  type: other
  lifecycle: unknown
  owner: hghtwr-group
